sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before_install:
  - npm --version
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - bash <(curl -s https://codecov.io/bash) -t aba6fce6-2ea8-4a36-bbb1-e94b007b4890
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
